### ISSUE TITLE
Balance confirmed on block explorer, but electrum still showing zero balance.

### ISSUE THREAD

**Issue by AVaz1990** [ZclassicCommunity/electrum-zcl#38]
I just downloaded the lastest version of the electrum wallet v3.2.6 win64 for windows. I moved my zcl from the exchange to the wallet but after 4 days of waiting the balance still shows zero. 

I have looked up my wallet address on the block explorer and the address shows confirmed for the exact amount I sent which leads me to believe the transaction went through.

I've tried to manually load the transaction through the "load transaction" option in the "Tools" drop down menu using the block transaction number, but it will not upload. I even tried scanning the QR code and was still unsuccessful. I then tried to restore the wallet and uploaded my wallet using the private keys, but I STILL have a balance of zero.

Any ideas as to why this is not fully processing to my wallet? I'm not too worried since I can see the transaction confirmed on the explorer and I have my private keys for that wallet, but I would like resolve this soon as I would like my ability to move funds to an exchange if an opportunity arises. 

Thanks in advance for any support.

**Comment by Homskiy** [comment]
Same issue...

**Comment by AVaz1990** [comment]
I have received my coins. Just thought I would update.

I had to manually change the server in order the connect to the network.

Basically go to the "Tools" drop down menu and select "Network"

Go to the server tab. You'll see the "select server automatically" box checked and you'll also see it says "electrum.800crypto.club". 
Uncheck the box to manually select the server and change it to "electrum.zcl.community"

Give it a second and your transaction should go through almost immediately.
